### ISSUE TITLE
Clean up feedstocks still using `conda-forge-ci-setup=3`

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge.github.io#2282]
I noticed this in [pytorch](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/256), and according to a [search](https://github.com/search?q=org%3Aconda-forge%20%2Fconda-forge-ci-setup%3D3%2F%20path%3Aconda-forge.yml&type=code) for this, we have around 10 feedstocks that are currently affected.

The problem with this is that using such an old ci-setup forces a very old conda-build, which is - pretty much by sheer luck - just _barely_ new enough to correctly handle [`{{ stdlib("c") }}`](https://github.com/conda-forge/conda-forge.github.io/issues/2102), which we need to avoid creating packages with incorrect metadata on osx/linux.

There are many other relevant changes that should make us retry to make these feedstocks use up-to-date build tools (some may still need to keep pinning lief due to various issues, but aside from a performance [regression](https://github.com/conda-forge/lief-feedstock/issues/45) on osx, lief 0.14 should have fixed most things).

* [x] [atheris](https://github.com/conda-forge/atheris-feedstock/blob/b09ef67701924925c5989d47031b57ed8a91b2d4/conda-forge.yml#L11) @conda-forge/atheris 
* [x] [ifcopenshell](https://github.com/conda-forge/ifcopenshell-feedstock/blob/ef0d1fd464919fb813d828a85248e420ec6f6eaa/conda-forge.yml#L13) @conda-forge/ifcopenshell 
* [x] [libignition-common](https://github.com/conda-forge/libignition-common-feedstock/blob/ef6b3c78914d2cd75cb7226a578e4a0d49b198ce/conda-forge.yml#L19) @conda-forge/libignition-common 
* [x] [orocos-kdl](https://github.com/conda-forge/orocos-kdl-feedstock/blob/fab577483e5a161ffc7b9f4ca80de14185ad3cfb/conda-forge.yml#L16) @conda-forge/orocos-kdl 
* [x] [pcl](https://github.com/conda-forge/pcl-feedstock/blob/be508a0b96bb56c5dbff8bd79707e2d5a7374444/conda-forge.yml#L17) @conda-forge/pcl
* [x] [python](https://github.com/conda-forge/python-feedstock/blob/03cc592ca36c332a10843c046d8e82125ca21e4e/conda-forge.yml#L18) @conda-forge/python
* [x] [pytorch](https://github.com/conda-forge/pytorch-cpu-feedstock/blob/6dd85b3f85a72371b2d3ccf6a386de67e61d667e/conda-forge.yml#L30) @conda-forge/pytorch-cpu 
* [x] [qt-main](https://github.com/conda-forge/qt-main-feedstock/blob/5f5c3f76b963e6f2dadcb4010e4b1e2a9eeb7cd3/conda-forge.yml#L34) @conda-forge/qt-main 
* [x] [stackvana-afw](https://github.com/conda-forge/stackvana-afw-feedstock/blob/db7b2ca6d837a8d92f1048f0df80d651afd1aba8/conda-forge.yml#L3) @conda-forge/stackvana-afw
* [x] [tlsh](https://github.com/conda-forge/tlsh-feedstock/blob/f7c2e2f4e3fe1f80cbf6ec59668962cf5248efa1/conda-forge.yml#L7) @conda-forge/tlsh 
* [x] [xgems](https://github.com/conda-forge/xgems-feedstock/blob/2ee0d4cb7cd4d255dd77feebba19849593ad5ccb/conda-forge.yml#L7) @conda-forge/xgems

**Comment by Krande** [comment]
@h-vetinari Okay, so all we need to do is to remove the `remote_ci_setup` entries and check to see if all goes well?

We are currently preparing a new release of `ifcopenshell` in https://github.com/conda-forge/ifcopenshell-feedstock/pull/54. So I will try to make the changes there to see if that goes well.

Here's what we have. I remember pinning py-lief was necessary way back when due to the osx builds ran out of time. Changing the py-lief version at the time fixed it. Hopefully this is gone now.

Here's the `remote_ci_setup` in ifcopenshell
```
remote_ci_setup:
- conda-forge-ci-setup=3
- py-lief>=0.12.3
```

**Comment by Krande** [comment]
@h-vetinari ifcopenshell is updated with the outdated configs removed.

**Comment by bollwyvl** [comment]
`tlsh` is fixed (well, [building](https://github.com/conda-forge/tlsh-feedstock/runs/29581870184))... I could probably use an assist on https://github.com/conda-forge/atheris-feedstock/pull/16 (my c++ chops are non-existent):

```
src/native/counters.cc:26:6: error: variable or field '__sanitizer_cov_8bit_counters_init' declared void
   26 | void __sanitizer_cov_8bit_counters_init(uint8_t* start, uint8_t* stop);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/native/counters.cc:26:41: error: 'uint8_t' was not declared in this scope
   26 | void __sanitizer_cov_8bit_counters_init(uint8_t* start, uint8_t* stop);
      |                                         ^~~~~~~
src/native/counters.cc:24:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   23 | #include "macros.h"
  +++ |+#include <cstdint>

```

**Comment by Tobias-Fischer** [comment]
@bollwyvl: this patch should fix it: https://patch-diff.githubusercontent.com/raw/google/atheris/pull/91.patch

**Comment by bollwyvl** [comment]
Thanks! Still seeing some OSX issues on `atheris` (but _not_ missing `libfuzzer`, which was happening previously)
