### ISSUE TITLE
Maintainer list not updating

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/conda-forge.github.io#324]
I am on the maintainer list to

zeromq, clangdev and llvmdev although I have not gotten the merge privileges yet.

**Comment by jakirkham** [comment]
Yeah there was an issue with a maintainer who had changed their handle. We corrected, but it seems there was some transient network issue in the recent run. If someone from @conda-forge/core could press the restart button on Travis CI `master` here, that should hopefully correct the issue once it runs.

**Comment by SylvainCorlay** [comment]
I eventually got commit rights in llvmdev and clangdev but I a still missing zeromq.

**Comment by jakirkham** [comment]
There appears to be rate limiting while running the team update script for the past few days. I think we are actually going to have to move all the team update code to a new asynchronous web service to actually keep up. That being said, I don't have time to work on it near term.

xref: https://github.com/conda-forge/conda-forge-webservices/issues/63

**Comment by jakirkham** [comment]
For the first time in a month, it appears to have [completed]( https://travis-ci.org/conda-forge/conda-forge.github.io/builds/204489136 ). That said, I'm still inclined to move these things into web services.
